### ISSUE TITLE
UI Changes todo

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#41]
- [ ] Add cursor pointer to mark as paid button
- [ ] Add cursor pointer and make + button bigger on calendar
- [ ] Disable cursor pointer on holidays and remove hover colors so it doesn't look like you can click it.
- [ ] make landing page respect widths again
- [ ] make today page not change widths when you add to the cut list
- [ ] give text to the print and edit buttons on the today page
